services:
  backend:
    build:
      context: . # Use the parent directory (MECO APP) as the build context
      dockerfile: ./Backend/Dockerfile
    image: ejposadas/mecoapp-backend
    container_name: backend
    env_file:
      - ./Backend/.env
      - ./Data_Loading/.env
    environment:
      - IS_DOCKER=true
      - NODE_ENV=production
    ports:
      - "3000:3000"
      # - "3004:3004"
    volumes:
      - "./Data_Loading:/app/Data_Loading"
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: . # This points to the root of your project, so everything in the parent directory will be accessible
      dockerfile: ./Frontend/Dockerfile
    image: ejposadas/mecoapp-frontend
    container_name: frontend
    env_file: ./Frontend/.env
    ports:
      - "80:80"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
