services:
  backend:
    build:
      context: . # Use the parent directory (MECO APP) as the build context
      dockerfile: ./Backend/Dockerfile
    container_name: backend
    env_file: 
      - ./Backend/.env
      - ./Data_Loading/.env
    environment:
      - IS_DOCKER=true
    ports:
      - "3000:3000"
    volumes:
      - "./Data_Loading:/app/Data_Loading"
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: . # This points to the root of your project, so everything in the parent directory will be accessible
      dockerfile: ./Frontend/Dockerfile
    container_name: frontend
    env_file: ./Frontend/.env
    ports:
      - "80:80"
    networks:
      - app-network
    restart: always

  proxy:
    image: nginx:alpine
    container_name: proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Mount the full nginx.conf file
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
