version: '3'

services:
  backend:
    build: ./backend
    container_name: backend
    env_file: ./backend/.env
    ports:
      - "3000:3000"
    volumes:
      # Optionally mount the data-loading folder if you want to update it without rebuilding:
      - ./data-loading:/app/data-loading
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    env_file: ./frontend/.env
    ports:
      - "80:80"
    networks:
      - app-network

  proxy:
    image: nginx:alpine
    container_name: proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
